### ISSUE TITLE
Does not ignore OSX attribute files when applying updates

### ISSUE THREAD

**Issue by sammargh** [profi200/sysUpdater#10]
On OSX when you put in a thumb drive/sd card it does this really stupid thing where it creates a file for extended attributes and names it ._filename in any folder you navigate.

sysUpdater tries to run these ._filename.cia files and returns an invalid signature which causes the upgrade process to fail. If you manually delete the ._* files within the updates directory it functions properly. Simple workaround is to ignore any .cia file that begins with ._ in the file name.

**Comment by profi200** [comment]
For fucks sake what were the people at Apple smoking? That's really annoying and i need to include an extra rule for the file filter.
I will later look into it.

**Comment by profi200** [comment]
Should be fixed with https://github.com/profi200/sysUpdater/commit/fed1587863db9faed51b32c52f4e92d96f6362f4
