### ISSUE TITLE
Some error when compiling...

### ISSUE THREAD

**Issue by mariogamer2** [profi200/sysUpdater#11]
When compiling with ubuntu 15.10,its give me:

fs.cpp
arm-none-eabi-g++ -MMD -MP -MF /opt/sysUpdater/build/fs.d -g -Wall -O3 -flto -mword-relocations -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/opt/sysUpdater/include -I/opt/sysUpdater/include/zip -I/opt/devkitpro/libctru/include -I/opt/sysUpdater/build -DARM11 -D_3DS -std=gnu++14 -c /opt/sysUpdater/source/fs.cpp -o fs.o 
In file included from /opt/sysUpdater/include/fs.h:29:0,
                 from /opt/sysUpdater/source/fs.cpp:26:
/opt/sysUpdater/include/zip/zip.h:50:18: fatal error: zlib.h: No such file or directory
compilation terminated.
/opt/devkitpro/devkitARM/base_rules:79: recipe for target 'fs.o' failed
make[1]: *** [fs.o] Error 1
Makefile:131: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by profi200** [comment]
That's because i did not strip out the zip stuff in fs.h and fs.cpp. It is not needed for this app to work.

**Comment by mariogamer2** [comment]
how to fix the build?

**Comment by profi200** [comment]
Remove -lz from the build flags in the makefile and comment out all the zip functions in fs.h and fs.c. There comes nothing important after it so you can just use /**/.

I really should remove that myself.

**Comment by mariogamer2** [comment]
I don't won't to do it.

I'm not a dev :)

**Comment by mariogamer2** [comment]
After f0db2b34adc70e6ebd6f775931ab082399d79129  I'ts give me another error:

fs.cpp
arm-none-eabi-g++ -MMD -MP -MF /opt/sysUpdater/build/fs.d -g -Wall -O3 -flto -mword-relocations -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/opt/sysUpdater/include -I/opt/sysUpdater/include/zip -I/opt/devkitpro/libctru/include -I/opt/sysUpdater/build -DARM11 -D_3DS -std=gnu++14 -c /opt/sysUpdater/source/fs.cpp -o fs.o 
/opt/sysUpdater/source/fs.cpp:589:85: warning: "/*" within comment [-Wcomment]
 -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY, nullptr, 0, 0, 0x800 /* UTF-8 fl
                                                                     ^
/opt/sysUpdater/source/fs.cpp:626:47: warning: "/*" within comment [-Wcomment]
              0, 0, 0, 0, nullptr, 0, 0, 0x800 /* UTF-8 flag )) != ZIP_OK)
                                               ^
In file included from /opt/sysUpdater/include/zip/zip.h:50:0,
                 from /opt/sysUpdater/include/fs.h:29,
                 from /opt/sysUpdater/source/fs.cpp:26:
/opt/sysUpdater/include/zip/ioapi.h:134:18: error: ISO C++ forbids declaration of 'voidpf' with no type [-fpermissive]
 typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char
                  ^
/opt/sysUpdater/include/zip/ioapi.h:134:18: error: typedef 'voidpf' is initialized (use decltype instead)
/opt/sysUpdater/include/zip/ioapi.h:134:30: error: 'open_file_func' was not declared in this scope
 typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char
                              ^
/opt/sysUpdater/include/zip/ioapi.h:135:18: error: ISO C++ forbids declaration of 'uLong' with no type [-fpermissive]
 typedef uLong    (ZCALLBACK *read_file_func)      OF((voidpf opaque, voidpf str
                  ^
/opt/sysUpdater/include/zip/ioapi.h:135:18: error: typedef 'uLong' is initialized (use decltype instead)
/opt/sysUpdater/include/zip/ioapi.h:135:30: error: 'read_file_func' was not declared in this scope
 typedef uLong    (ZCALLBACK *read_file_func)      OF((voidpf opaque, voidpf str
                              ^
/opt/sysUpdater/include/zip/ioapi.h:136:18: error: ISO C++ forbids declaration of 'uLong' with no type [-fpermissive]
 typedef uLong    (ZCALLBACK *write_file_func)     OF((voidpf opaque, voidpf str
                  ^
/opt/sysUpdater/include/zip/ioapi.h:136:18: error: typedef 'uLong' is initialized (use decltype instead)
/opt/sysUpdater/include/zip/ioapi.h:136:30: error: 'write_file_func' was not declared in this scope
 typedef uLong    (ZCALLBACK *write_file_func)     OF((voidpf opaque, voidpf str
                              ^
/opt/sysUpdater/include/zip/ioapi.h:137:51: error: expected initializer before 'OF'
 typedef int      (ZCALLBACK *close_file_func)     OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:138:51: error: expected initializer before 'OF'
 typedef int      (ZCALLBACK *testerror_file_func) OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:140:51: error: expected initializer before 'OF'
 typedef long     (ZCALLBACK *tell_file_func)      OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:141:51: error: expected initializer before 'OF'
 typedef long     (ZCALLBACK *seek_file_func)      OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:147:5: error: 'open_file_func' does not name a type
     open_file_func      zopen_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:148:5: error: 'read_file_func' does not name a type
     read_file_func      zread_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:149:5: error: 'write_file_func' does not name a type
     write_file_func     zwrite_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:150:5: error: 'tell_file_func' does not name a type
     tell_file_func      ztell_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:151:5: error: 'seek_file_func' does not name a type
     seek_file_func      zseek_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:152:5: error: 'close_file_func' does not name a type
     close_file_func     zclose_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:153:5: error: 'testerror_file_func' does not name a type
     testerror_file_func zerror_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:154:5: error: 'voidpf' does not name a type
     voidpf              opaque;
     ^
/opt/sysUpdater/include/zip/ioapi.h:157:51: error: expected initializer before 'OF'
 typedef ZPOS64_T (ZCALLBACK *tell64_file_func)    OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:158:51: error: expected initializer before 'OF'
 typedef long     (ZCALLBACK *seek64_file_func)    OF((voidpf opaque, voidpf str
                                                   ^
/opt/sysUpdater/include/zip/ioapi.h:159:18: error: ISO C++ forbids declaration of 'voidpf' with no type [-fpermissive]
 typedef voidpf   (ZCALLBACK *open64_file_func)    OF((voidpf opaque, const void
                  ^
/opt/sysUpdater/include/zip/ioapi.h:159:18: error: typedef 'voidpf' is initialized (use decltype instead)
/opt/sysUpdater/include/zip/ioapi.h:159:30: error: 'open64_file_func' was not declared in this scope
 typedef voidpf   (ZCALLBACK *open64_file_func)    OF((voidpf opaque, const void
                              ^
/opt/sysUpdater/include/zip/ioapi.h:163:5: error: 'open64_file_func' does not name a type
     open64_file_func    zopen64_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:164:5: error: 'read_file_func' does not name a type
     read_file_func      zread_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:165:5: error: 'write_file_func' does not name a type
     write_file_func     zwrite_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:166:5: error: 'tell64_file_func' does not name a type
     tell64_file_func    ztell64_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:167:5: error: 'seek64_file_func' does not name a type
     seek64_file_func    zseek64_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:168:5: error: 'close_file_func' does not name a type
     close_file_func     zclose_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:169:5: error: 'testerror_file_func' does not name a type
     testerror_file_func zerror_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:170:5: error: 'voidpf' does not name a type
     voidpf              opaque;
     ^
/opt/sysUpdater/include/zip/ioapi.h:173:28: error: expected initializer before 'OF'
 void fill_fopen64_filefunc OF((zlib_filefunc64_def* pzlib_filefunc_def));
                            ^
/opt/sysUpdater/include/zip/ioapi.h:174:26: error: expected initializer before 'OF'
 void fill_fopen_filefunc OF((zlib_filefunc_def* pzlib_filefunc_def));
                          ^
/opt/sysUpdater/include/zip/ioapi.h:180:5: error: 'open_file_func' does not name a type
     open_file_func      zopen32_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:181:5: error: 'tell_file_func' does not name a type
     tell_file_func      ztell32_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:182:5: error: 'seek_file_func' does not name a type
     seek_file_func      zseek32_file;
     ^
/opt/sysUpdater/include/zip/ioapi.h:193:1: error: 'voidpf' does not name a type
 voidpf call_zopen64 OF((const zlib_filefunc64_32_def* pfilefunc,const void*file
 ^
/opt/sysUpdater/include/zip/ioapi.h:194:22: error: expected initializer before 'OF'
 long    call_zseek64 OF((const zlib_filefunc64_32_def* pfilefunc,voidpf filestr
                      ^
/opt/sysUpdater/include/zip/ioapi.h:195:23: error: expected initializer before 'OF'
 ZPOS64_T call_ztell64 OF((const zlib_filefunc64_32_def* pfilefunc,voidpf filest
                       ^
In file included from /opt/sysUpdater/include/fs.h:29:0,
                 from /opt/sysUpdater/source/fs.cpp:26:
/opt/sysUpdater/include/zip/zip.h:65:9: error: 'voidp' does not name a type
 typedef voidp zipFile;
         ^
/opt/sysUpdater/include/zip/zip.h:87:5: error: 'uInt' does not name a type
     uInt tm_sec;            /* seconds after the minute - [0,59] */
     ^
/opt/sysUpdater/include/zip/zip.h:88:5: error: 'uInt' does not name a type
     uInt tm_min;            /* minutes after the hour - [0,59] */
     ^
/opt/sysUpdater/include/zip/zip.h:89:5: error: 'uInt' does not name a type
     uInt tm_hour;           /* hours since midnight - [0,23] */
     ^
/opt/sysUpdater/include/zip/zip.h:90:5: error: 'uInt' does not name a type
     uInt tm_mday;           /* day of the month - [1,31] */
     ^
/opt/sysUpdater/include/zip/zip.h:91:5: error: 'uInt' does not name a type
     uInt tm_mon;            /* months since January - [0,11] */
     ^
/opt/sysUpdater/include/zip/zip.h:92:5: error: 'uInt' does not name a type
     uInt tm_year;           /* years - [1980..2044] */
     ^
/opt/sysUpdater/include/zip/zip.h:98:5: error: 'uLong' does not name a type
     uLong       dosDate;       /* if dos_date == 0, tmu_date is used      */
     ^
/opt/sysUpdater/include/zip/zip.h:101:5: error: 'uLong' does not name a type
     uLong       internal_fa;    /* internal file attributes        2 bytes */
     ^
/opt/sysUpdater/include/zip/zip.h:102:5: error: 'uLong' does not name a type
     uLong       external_fa;    /* external file attributes        4 bytes */
     ^
/opt/sysUpdater/include/zip/zip.h:112:8: error: 'zipFile' does not name a type
 extern zipFile ZEXPORT zipOpen OF((const char *pathname, int append));
        ^
/opt/sysUpdater/include/zip/zip.h:113:8: error: 'zipFile' does not name a type
 extern zipFile ZEXPORT zipOpen64 OF((const void *pathname, int append));
        ^
/opt/sysUpdater/include/zip/zip.h:133:8: error: 'zipFile' does not name a type
 extern zipFile ZEXPORT zipOpen2 OF((const void *pathname,
        ^
/opt/sysUpdater/include/zip/zip.h:138:8: error: 'zipFile' does not name a type
 extern zipFile ZEXPORT zipOpen2_64 OF((const void *pathname,
        ^
/opt/sysUpdater/include/zip/zip.h:143:20: error: expected initializer before 'zipOpenNewFileInZip'
 extern int ZEXPORT zipOpenNewFileInZip OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:154:20: error: expected initializer before 'zipOpenNewFileInZip64'
 extern int ZEXPORT zipOpenNewFileInZip64 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:183:20: error: expected initializer before 'zipOpenNewFileInZip2'
 extern int ZEXPORT zipOpenNewFileInZip2 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:196:20: error: expected initializer before 'zipOpenNewFileInZip2_64'
 extern int ZEXPORT zipOpenNewFileInZip2_64 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:212:20: error: expected initializer before 'zipOpenNewFileInZip3'
 extern int ZEXPORT zipOpenNewFileInZip3 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:229:20: error: expected initializer before 'zipOpenNewFileInZip3_64'
 extern int ZEXPORT zipOpenNewFileInZip3_64 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:255:20: error: expected initializer before 'zipOpenNewFileInZip4'
 extern int ZEXPORT zipOpenNewFileInZip4 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:276:20: error: expected initializer before 'zipOpenNewFileInZip4_64'
 extern int ZEXPORT zipOpenNewFileInZip4_64 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:303:20: error: expected initializer before 'zipWriteInFileInZip'
 extern int ZEXPORT zipWriteInFileInZip OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:310:20: error: expected initializer before 'zipCloseFileInZip'
 extern int ZEXPORT zipCloseFileInZip OF((zipFile file));
                    ^
/opt/sysUpdater/include/zip/zip.h:315:20: error: expected initializer before 'zipCloseFileInZipRaw'
 extern int ZEXPORT zipCloseFileInZipRaw OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:319:20: error: expected initializer before 'zipCloseFileInZipRaw64'
 extern int ZEXPORT zipCloseFileInZipRaw64 OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:329:20: error: expected initializer before 'zipClose'
 extern int ZEXPORT zipClose OF((zipFile file,
                    ^
/opt/sysUpdater/include/zip/zip.h:336:20: error: expected initializer before 'zipRemoveExtraInfoBlock'
 extern int ZEXPORT zipRemoveExtraInfoBlock OF((char* pData, int* dataLen, short
                    ^
In file included from /opt/sysUpdater/source/fs.cpp:29:0:
/opt/sysUpdater/include/zip/unzip.h:66:9: error: 'voidp' does not name a type
 typedef voidp unzFile;
         ^
/opt/sysUpdater/include/zip/unzip.h:82:5: error: 'uInt' does not name a type
     uInt tm_sec;            /* seconds after the minute - [0,59] */
     ^
/opt/sysUpdater/include/zip/unzip.h:83:5: error: 'uInt' does not name a type
     uInt tm_min;            /* minutes after the hour - [0,59] */
     ^
/opt/sysUpdater/include/zip/unzip.h:84:5: error: 'uInt' does not name a type
     uInt tm_hour;           /* hours since midnight - [0,23] */
     ^
/opt/sysUpdater/include/zip/unzip.h:85:5: error: 'uInt' does not name a type
     uInt tm_mday;           /* day of the month - [1,31] */
     ^
/opt/sysUpdater/include/zip/unzip.h:86:5: error: 'uInt' does not name a type
     uInt tm_mon;            /* months since January - [0,11] */
     ^
/opt/sysUpdater/include/zip/unzip.h:87:5: error: 'uInt' does not name a type
     uInt tm_year;           /* years - [1980..2044] */
     ^
/opt/sysUpdater/include/zip/unzip.h:96:5: error: 'uLong' does not name a type
     uLong size_comment;         /* size of the global comment of the zipfile */
     ^
/opt/sysUpdater/include/zip/unzip.h:101:5: error: 'uLong' does not name a type
     uLong number_entry;         /* total number of entries in
     ^
/opt/sysUpdater/include/zip/unzip.h:103:5: error: 'uLong' does not name a type
     uLong size_comment;         /* size of the global comment of the zipfile */
     ^
/opt/sysUpdater/include/zip/unzip.h:109:5: error: 'uLong' does not name a type
     uLong version;              /* version made by                 2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:110:5: error: 'uLong' does not name a type
     uLong version_needed;       /* version needed to extract       2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:111:5: error: 'uLong' does not name a type
     uLong flag;                 /* general purpose bit flag        2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:112:5: error: 'uLong' does not name a type
     uLong compression_method;   /* compression method              2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:113:5: error: 'uLong' does not name a type
     uLong dosDate;              /* last mod file date in Dos fmt   4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:114:5: error: 'uLong' does not name a type
     uLong crc;                  /* crc-32                          4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:117:5: error: 'uLong' does not name a type
     uLong size_filename;        /* filename length                 2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:118:5: error: 'uLong' does not name a type
     uLong size_file_extra;      /* extra field length              2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:119:5: error: 'uLong' does not name a type
     uLong size_file_comment;    /* file comment length             2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:121:5: error: 'uLong' does not name a type
     uLong disk_num_start;       /* disk number start               2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:122:5: error: 'uLong' does not name a type
     uLong internal_fa;          /* internal file attributes        2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:123:5: error: 'uLong' does not name a type
     uLong external_fa;          /* external file attributes        4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:130:5: error: 'uLong' does not name a type
     uLong version;              /* version made by                 2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:131:5: error: 'uLong' does not name a type
     uLong version_needed;       /* version needed to extract       2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:132:5: error: 'uLong' does not name a type
     uLong flag;                 /* general purpose bit flag        2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:133:5: error: 'uLong' does not name a type
     uLong compression_method;   /* compression method              2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:134:5: error: 'uLong' does not name a type
     uLong dosDate;              /* last mod file date in Dos fmt   4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:135:5: error: 'uLong' does not name a type
     uLong crc;                  /* crc-32                          4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:136:5: error: 'uLong' does not name a type
     uLong compressed_size;      /* compressed size                 4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:137:5: error: 'uLong' does not name a type
     uLong uncompressed_size;    /* uncompressed size               4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:138:5: error: 'uLong' does not name a type
     uLong size_filename;        /* filename length                 2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:139:5: error: 'uLong' does not name a type
     uLong size_file_extra;      /* extra field length              2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:140:5: error: 'uLong' does not name a type
     uLong size_file_comment;    /* file comment length             2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:142:5: error: 'uLong' does not name a type
     uLong disk_num_start;       /* disk number start               2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:143:5: error: 'uLong' does not name a type
     uLong internal_fa;          /* internal file attributes        2 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:144:5: error: 'uLong' does not name a type
     uLong external_fa;          /* external file attributes        4 bytes */
     ^
/opt/sysUpdater/include/zip/unzip.h:149:20: error: expected initializer before 'unzStringFileNameCompare'
 extern int ZEXPORT unzStringFileNameCompare OF ((const char* fileName1,
                    ^
/opt/sysUpdater/include/zip/unzip.h:162:8: error: 'unzFile' does not name a type
 extern unzFile ZEXPORT unzOpen OF((const char *path));
        ^
/opt/sysUpdater/include/zip/unzip.h:163:8: error: 'unzFile' does not name a type
 extern unzFile ZEXPORT unzOpen64 OF((const void *path));
        ^
/opt/sysUpdater/include/zip/unzip.h:180:8: error: 'unzFile' does not name a type
 extern unzFile ZEXPORT unzOpen2 OF((const void *path,
        ^
/opt/sysUpdater/include/zip/unzip.h:187:8: error: 'unzFile' does not name a type
 extern unzFile ZEXPORT unzOpen2_64 OF((const void *path,
        ^
/opt/sysUpdater/include/zip/unzip.h:194:20: error: expected initializer before 'unzClose'
 extern int ZEXPORT unzClose OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:201:20: error: expected initializer before 'unzGetGlobalInfo'
 extern int ZEXPORT unzGetGlobalInfo OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:204:20: error: expected initializer before 'unzGetGlobalInfo64'
 extern int ZEXPORT unzGetGlobalInfo64 OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:212:20: error: expected initializer before 'unzGetGlobalComment'
 extern int ZEXPORT unzGetGlobalComment OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:225:20: error: expected initializer before 'unzGoToFirstFile'
 extern int ZEXPORT unzGoToFirstFile OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:231:20: error: expected initializer before 'unzGoToNextFile'
 extern int ZEXPORT unzGoToNextFile OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:238:20: error: expected initializer before 'unzLocateFile'
 extern int ZEXPORT unzLocateFile OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:256:5: error: 'uLong' does not name a type
     uLong pos_in_zip_directory;   /* offset in zip file directory */
     ^
/opt/sysUpdater/include/zip/unzip.h:257:5: error: 'uLong' does not name a type
     uLong num_of_file;            /* # of file */
     ^
/opt/sysUpdater/include/zip/unzip.h:260:20: error: expected initializer before 'unzGetFilePos'
 extern int ZEXPORT unzGetFilePos(
                    ^
/opt/sysUpdater/include/zip/unzip.h:264:20: error: expected initializer before 'unzGoToFilePos'
 extern int ZEXPORT unzGoToFilePos(
                    ^
/opt/sysUpdater/include/zip/unzip.h:274:20: error: expected initializer before 'unzGetFilePos64'
 extern int ZEXPORT unzGetFilePos64(
                    ^
/opt/sysUpdater/include/zip/unzip.h:278:20: error: expected initializer before 'unzGoToFilePos64'
 extern int ZEXPORT unzGoToFilePos64(
                    ^
/opt/sysUpdater/include/zip/unzip.h:284:20: error: expected initializer before 'unzGetCurrentFileInfo64'
 extern int ZEXPORT unzGetCurrentFileInfo64 OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:293:20: error: expected initializer before 'unzGetCurrentFileInfo'
 extern int ZEXPORT unzGetCurrentFileInfo OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:317:25: error: expected initializer before 'unzGetCurrentFileZStreamPos64'
 extern ZPOS64_T ZEXPORT unzGetCurrentFileZStreamPos64 OF((unzFile file));
                         ^
/opt/sysUpdater/include/zip/unzip.h:327:20: error: expected initializer before 'unzOpenCurrentFile'
 extern int ZEXPORT unzOpenCurrentFile OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:333:20: error: expected initializer before 'unzOpenCurrentFilePassword'
 extern int ZEXPORT unzOpenCurrentFilePassword OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:341:20: error: expected initializer before 'unzOpenCurrentFile2'
 extern int ZEXPORT unzOpenCurrentFile2 OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:354:20: error: expected initializer before 'unzOpenCurrentFile3'
 extern int ZEXPORT unzOpenCurrentFile3 OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:369:20: error: expected initializer before 'unzCloseCurrentFile'
 extern int ZEXPORT unzCloseCurrentFile OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:375:20: error: expected initializer before 'unzReadCurrentFile'
 extern int ZEXPORT unzReadCurrentFile OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:389:8: error: 'z_off_t' does not name a type
 extern z_off_t ZEXPORT unztell OF((unzFile file));
        ^
/opt/sysUpdater/include/zip/unzip.h:391:25: error: expected initializer before 'unztell64'
 extern ZPOS64_T ZEXPORT unztell64 OF((unzFile file));
                         ^
/opt/sysUpdater/include/zip/unzip.h:396:20: error: expected initializer before 'unzeof'
 extern int ZEXPORT unzeof OF((unzFile file));
                    ^
/opt/sysUpdater/include/zip/unzip.h:401:20: error: expected initializer before 'unzGetLocalExtrafield'
 extern int ZEXPORT unzGetLocalExtrafield OF((unzFile file,
                    ^
/opt/sysUpdater/include/zip/unzip.h:420:25: error: expected initializer before 'unzGetOffset64'
 extern ZPOS64_T ZEXPORT unzGetOffset64 (unzFile file);
                         ^
/opt/sysUpdater/include/zip/unzip.h:421:8: error: 'uLong' does not name a type
 extern uLong ZEXPORT unzGetOffset (unzFile file);
        ^
/opt/sysUpdater/include/zip/unzip.h:424:20: error: expected initializer before 'unzSetOffset64'
 extern int ZEXPORT unzSetOffset64 (unzFile file, ZPOS64_T pos);
                    ^
/opt/sysUpdater/include/zip/unzip.h:425:20: error: expected initializer before 'unzSetOffset'
 extern int ZEXPORT unzSetOffset (unzFile file, uLong pos);
                    ^
/opt/devkitpro/devkitARM/base_rules:79: recipe for target 'fs.o' failed
make[1]: *** [fs.o] Error 1
Makefile:131: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by profi200** [comment]
Please use a gist next time. That's annoying with such long logs.

God is that a mess. I will disable the unnecessary stuff and maybe fix the other issue with the stupid attribute files from OSX.

**Comment by profi200** [comment]
The latest version should compile fine with the newest devkitARM and newest ctrulib.
