### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by shadowofdarkness** [profi200/sysUpdater#17]
This is the error I'm getting trying to compile the current source  on a Linux machine with the newest devkitARM and newest ctrulib.

http://pastebin.com/QUUcmwFs

commit fed1587863db9faed51b32c52f4e92d96f6362f4

**Comment by profi200** [comment]
You are not using the latest ctrulib from git.

**Comment by shadowofdarkness** [comment]
Thanks, I didn't realize I needed from git.
