### ISSUE TITLE
NO ARM11 Message

### ISSUE THREAD

**Issue by LucianoNeo** [profi200/sysUpdater#19]
No numbers from #1 to #8 for me , just the buttons options.. 
No Success message, no error message....
Old 3ds 10.3
What to do???

**Comment by profi200** [comment]
I don't understand what you try to tell me here.

**Comment by LucianoNeo** [comment]
Ok.  Let's go... 
I have an old 3ds with 10.3 firwmare
I want to downgrade it to 9.2.0
I already have all the files in SDcard
I already installed menuhax
But when I open sysUpdater 
I don't see this parameters in the screen 
ARM11
#1 BLABLALBA
#2 BLABLABLA
#3 ETC... 

It only show me the options. 
A to upgrade 
Y to downgrade 

If I push any of this buttons,  the 3ds freezes....

**Comment by profi200** [comment]
My version does not have memchunkhax v2 attached. You must use one of the builds with memchunkhax v2.

https://github.com/profi200/sysUpdater/issues/18#issuecomment-169321992
