### ISSUE TITLE
Brick

### ISSUE THREAD

**Issue by urherenow** [profi200/sysUpdater#2]
This says the .3dsx version will not work. When you load it as .CIA, it says if you are running as CIA, close now. So... is it supposed to work at all? I hit "A" to watch it install everything and it bricked on the reboot command. I am hard-modded so I'm safe, but this program will definitely cause a lot of bricks and heartache!

**Comment by urherenow** [comment]
to clarify, I am trying from a downgraded sysnand to 9.2 update.

**Comment by profi200** [comment]
https://github.com/profi200/sysUpdater/commit/12bb22e5c51041c608ded8409e6942afef0e36fa#commitcomment-10547171

Gateway mode?

**Comment by urherenow** [comment]
Yes. I have no idea how to run a .cia otherwise. Please let me know if there is a way. It's very confusing that you ask sinse the source only compiles an .elf and .3dsx, yet doesn't work with Ninjhax....

**Comment by profi200** [comment]
It is made to update in a proper way instead of messing with the 3DS internal partitions on bare metal. The makefile is the standard ctrulib makefile. I would like to keep it as it is. I will see what i can do to upload my template for CIA building which does this separately without touching the original makefile.

**Comment by urherenow** [comment]
But this won't take care of the gateway mode issue. What is sorely needed is another way to launch a .cia. Problem is that if you're emphatically anti-P-word, I'm not sure there is a way to release something like that and still prevent said p-word :(

**Comment by profi200** [comment]
How should i detect it exactly? I i see no 100% safe way i could differentiate where this is running on.
Meh, stop it. I offer no one anything and i made my stance clear.
