### ISSUE TITLE
Does latest release is safe for update?

### ISSUE THREAD

**Issue by mariogamer2** [profi200/sysUpdater#21]
Does it is? I want to update a 2ds on 6.0.0 to 9.2.0.

**Comment by profi200** [comment]
Should be a lot safer than before. Updates were almost never a problem.

**Comment by mariogamer2** [comment]
Ok thank.Another question,if I test on emuNAND with rxTools,does this will brick emuNAND?

**Comment by profi200** [comment]
No.

Update ctrulib to the version from Github.

**Comment by mariogamer2** [comment]
Ok this can be closed,thank another time!

**Comment by mariogamer2** [comment]
Humm,CIA sysUpdater doesn't build

**Comment by profi200** [comment]
It uses some very old stuff to make banner and icon. Because i included prebuild banner and icon binaries all you need to do is build the CIA from it with makerom.

makerom -f cia -o sysUpdater.cia -elf sysUpdater.elf -rsf app/build-cia.rsf -icon app/icon.icn -banner app/banner.bnr -exefslogo -target t

**Comment by mariogamer2** [comment]
Where is the soft "makerom"?

**Comment by profi200** [comment]
See the "Project_CTR" repo i'm hosting.

**Comment by piratesephiroth** [comment]
So this latest version is at least as safe as the now defunct TuxSH's build for downgrading to 9.2, right?

**Comment by mariogamer2** [comment]
Yes of course

**Comment by profi200** [comment]
Remember that it does not include memchunkhax v2. If you need a build with it you need to ask the people who made the previous builds to make a new one based on latest changes.

**Comment by piratesephiroth** [comment]
Ah so it's not usable on 10.3 through memchuinkhax2. All right.
