### ISSUE TITLE
Newest version, O3DS, failed to get CIA file info

### ISSUE THREAD

**Issue by PokeyDoggo** [profi200/sysUpdater#23]
Hi, I'd like to share my experiences with sysupdate and downgrading.
I tried to downgrade with the newest version of sysupdate on this site, on a original3ds, with a 9.2.0-20E.
It gave this error: "getting cia file informations" " title exception: main.cpp:148 Result: 0xD900182f failed to get CIA file info
Some guy on reddit has this as well. 
https://www.reddit.com/r/3dshacks/comments/3zmzoq/getting_error_on_system_updater_n3ds_103/

As I've tried two different versions of 9.2.0-20E, I looked at another reddit thread, which linked to a guide I was using as well.
Anyway, the two Sysupdate files from this thread do work: 
https://gbatemp.net/threads/simple-guide-to-downgrading-your-3ds.407888/
Also after installation, rebooting does not take 10 seconds btw.
Waited more than I should. Got curious again, read up on this:
https://gbatemp.net/threads/tutorial-downgrade-3ds-with-sysupdater.407924/
''Q: It won't reboot after the finished downgrade.
A: What I did: Waited 10 minutes, then I powered it off. Downgrade suceed. You don't have another choice anyway.''
That worked. Had to wait those 10 seconds at a black screen after I restarted it.

Thanks for your help by writing this program.

**Comment by PokeyDoggo** [comment]
Oh as far as an issue goes.. I fixed it already. Just wanted to share my experiences.
I wonder what made the latest updates of systupdate not work on my 3ds though.

**Comment by darkunderdog** [comment]
@PokeyDoggo Would you share your fix for everyone?

**Comment by PokeyDoggo** [comment]
It's the sysupdate link from this thread: https://gbatemp.net/threads/simple-guide-to-downgrading-your-3ds.407888/
which is a direct download link to:
https://gbatemp.net/attachments/sysupdater-zip.34449/
Just replacing the two files of the newest sysupdate files in \3ds\sysUpdater, with the two older files in the GBA link fixed it for me.

**Comment by profi200** [comment]
The issue is not reading. The newest release explicitly says it does not come with memchunkhax v2.

**Comment by VlinkZ** [comment]
where can I get memchunkhax v2?
