### ISSUE TITLE
When ever I try to downgrade it says, "Failed to get CIA file info"

### ISSUE THREAD

**Issue by dev1niscool** [profi200/sysUpdater#24]
Are there any solutions?
I am on o3DS on 10.3 using menuhax, and ironhax

**Comment by naari3** [comment]
http://imgur.com/RuI0hqQ.jpg
me too.
I am on n3DS on 10.3 using menuhax only.

Getting CIA file informations...

titleException:
main.cpp:154: Result: 0xD900182F
Failed to get CIA file info!

**Comment by profi200** [comment]
README

The release says in bold text it does not include memchunkhax v2.

**Comment by dev1niscool** [comment]
FIGURED OUT HOW TO FIX IT, USE A WINDOWS COMPUTER NOT MAC
