### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by NgDTien** [profi200/sysUpdater#26]
titleException:
main.cpp:154:Result:0xD900182F
Failed to get CIA file info!

**Comment by profi200** [comment]
README

**Comment by ferbeb** [comment]
Sorry to bother you, but: I put the updates/*.cia folder on the root of my 64 GB microSD, tried both Browserhax and Menuhax multiple times, also tried launching the ftp server from the homebrew launcher before attempting to downgrade, still not getting anything else than the mentioned error. I verified the checksum of the downloaded 9.2.0-20E update package, even formatted my SD card again just to be sure. I'm using a New3DSXL.

**Comment by jo32** [comment]
tried like 70times using 0.4.2 and checking the md5 of cia downloaded by 3DNUS.exe, still get the same error.

**Comment by profi200** [comment]
Again, read what the release says. It clearly says it does not include memchunkhax v2.

**Comment by jo32** [comment]
I did this in Menuhax and browser hax.

**Comment by jo32** [comment]
Sorry for posting ignorant comments. I think most of those who submit issue like this, including me,  don't know memchunkhax v2 is the prerequisite for downgrading sysNand, which the official repo don't support.

I think adding more explanation in readme will be a great help.
