### ISSUE TITLE
"Failed to get CIA information"

### ISSUE THREAD

**Issue by PokeAcer549** [profi200/sysUpdater#30]
I keep getting the above error message on a 10.3 o3ds xl, whether 0.4.1 or 0.4.
I tried the FTP-3DS trick, to no avail, aswell

**Comment by Committee** [comment]
Are you trying to downgrade? If so this does not include the memchunk hax needed to do the downgrade.

**Comment by PokeAcer549** [comment]
It'd been nicer for it all to say that, thanks. What version do you know does?

**Comment by Committee** [comment]
Not sure if ok to mention or link here but your looking for the "safe" sysupdater version.

**Comment by PokeAcer549** [comment]
That one has been said to brick more than the other sysUpdater version tht was buggy.

**Comment by allenhai94** [comment]
I'm getting similar error as well.
I've been trying to upgrade my N3DS from 9.9 to 10.3.0-28u.
What I've done is I have successfully got homebrew up and running, installed manuhax_manager2.1.
Then put upgrade cia files in updates folder under root dir in sdcard, boot up 3ds into homebrew and run ftBRONY.
From here on I tried to use sysUpdater 0.4.2b to update, and I got stuck with error information:

titleException:
main.cpp:108: Result: 0xD900182F
Failed to get CIA file info!

I was not able to (from the source code) locate a plausable cause for such exception. Any pointers to help me figure out what could be the potential causes? Thanks.

**Comment by profi200** [comment]
I can't believe so much people overlook the bold text in the release which says it does not include memchunkhax v2. It will not work with *hax alone. Maybe i should make this more clear.

**Comment by Zetchzie** [comment]
just use cia version in rx mode thats the only way you can get full access

**Comment by PokeAcer549** [comment]
@profi200 this also occurs on previous versions.

**Comment by samcambolt270** [comment]
@Zetchzie @profi200 i also get this problem, and on versions which do include memchunkhax. where can i find this "cia version" zetchzi mentioned?

**Comment by Pearc** [comment]
hey, using n3ds xl on 9.6.0-24E where can i get a cia version in rx mode? cause i don't find any. get the cia information error too. btw great work :)

**Comment by olec04** [comment]
cia is for 9.2 cfw users/a9lh

**Comment by PokeAcer549** [comment]
I'm closing this, goddamn it:
If you have A9LH/CFW and want to downgrade or upgrade, use the CIA version. If you genuinely need memchunkhax for it, you use a different copy, however I'm so out of the loop for downgrading so IDK.
@profi200 sorry for bringing the spam.
