### ISSUE TITLE
(Question) Why firmware spoofing brick 3ds?

### ISSUE THREAD

**Issue by mariogamer2** [profi200/sysUpdater#34]
And what it is exactly?

**Comment by Zetchzie** [comment]
Yea id like to know this aswell and how we use the cia version thats recommended. because we cant use the cia without being in rxmode or dev mode.

**Comment by profi200** [comment]
Firmware spoofing makes the kernel version higher and if you try to install older NATIVE_FIRM it does not get correctly installed to NAND because it thinks it is up to date.

**Comment by TuxSH** [comment]
But now that AM_InstallFIRM is used instead of AM_InstallNATIVEFIRM even for upgrades, it shouldn't be an issue anymore (didn't test though).

**Comment by mariogamer2** [comment]
@TuxSH Asked on LS if anyone can do it :P

**Comment by mariogamer2** [comment]
Someone on the forum tested and he updated to 10.3 perfectly!

Closing...
