### ISSUE TITLE
not working on FW 9.9.0U

### ISSUE THREAD

**Issue by orangpelupa** [profi200/sysUpdater#36]
it just crash back to the homebrew launcher a few secs after pressing Y.

old 3DS FW 9.9.0U
IronHax launching ninjax and the homebrew launcher

**Comment by mariogamer2** [comment]
You have to pick the memchunkhax one.

**Comment by orangpelupa** [comment]
dunno if this one is memchunkhax one but it did nothing after pressing Y
https://github.com/Plailect/Guide/wiki/Part-2-(Downgrading)
"For versions 9.3.0 through 10.3.0: This https://mega.nz/#!10FjBKrB!PqbqJ8oSzoX-6iuhafR7kdHiWUBQSptrhjYTR6BLLUI version of sysUpdater"

**Comment by orangpelupa** [comment]
ok used the 4.1 (ithave memchunkhax2) and it says

"terminate called after throwing and instance of titleException
terminate called recursively"

**Comment by orangpelupa** [comment]
turns out it does work with 0.4.2b version, after 4 hours of trying it again and again :D
