### ISSUE TITLE
Log support?

### ISSUE THREAD

**Issue by mariogamer2** [profi200/sysUpdater#39]
Log can be usefull if an user brick and want to use cia from the net to unbrick. The log can be used to find the cia.

**Comment by profi200** [comment]
I don't really have the motivation to work on this tool anymore. There are alternatives now which may do it better like [PlaiSysUpdater](https://github.com/Plailect/PlaiSysUpdater). I have not seen anyone using my sysUpdater in a long time btw.

**Comment by mariogamer2** [comment]
Yes but PlaiSysUpdater is for 2.1.0 and 9.2 only...
