### ISSUE TITLE
Can't downgrade

### ISSUE THREAD

**Issue by lavanoid** [profi200/sysUpdater#4]
You think you could make this so that when a newer title is installed, it removes that title and installs the older version?

Thanks :)

**Comment by profi200** [comment]
It's possible but i had no plan yet to do that. I have not much time but an improved version was planned anyway. If i implement that then at least not automatically by default to prevent problems.

**Comment by lavanoid** [comment]
Okey doke. Can't wait :D

**Comment by profi200** [comment]
Updated

**Comment by lavanoid** [comment]
Cool! Thank you!
