### ISSUE TITLE
Failed to get CIA file info!

### ISSUE THREAD

**Issue by olec04** [profi200/sysUpdater#42]
titleException:
main.cpp:148: Result: 0xD900182F
O3ds 11.1 dsiware downgraded to native_firm 10.4

**Comment by Shadowrend** [comment]
Yeah me too

**Comment by mariogamer2** [comment]
Do you use SysDowngrader?

**Comment by Shadowrend** [comment]
no

**Comment by mariogamer2** [comment]
SysUpdater does not support higger firmware than 9.2.0.

**Comment by Shadowrend** [comment]
what should i use? sysdowngrader?

**Comment by mariogamer2** [comment]
yes

**Comment by Shadowrend** [comment]
ok thanks

**Comment by Shadowrend** [comment]
IT WORKED!! THANK YOU VERY MUCH!!!

**Comment by olec04** [comment]
Still doesn't work...

**Comment by olec04** [comment]
3DSisdent (Or whatever its called) says its still on the original native_firm...

**Comment by mariogamer2** [comment]
Not a sysupdater issue,create it on plailect guide.

**Comment by olec04** [comment]
K
