### ISSUE TITLE
fsException error on 11.14.0-46J N2DSXL upgrading to 11.15.0-47J

### ISSUE THREAD

**Issue by ghost** [profi200/sysUpdater#47]
I get an error when trying to update from my 11.14.0-46J N2DSXL (region changed from USA 2DSXL) to 11.15.0-47J.
I'm using Darth Sternie's firmware files. (System updater, even in Safe Mode, doesn't work)

The error I get is as follows:
```
Getting CIA file informations...

0004013020002F03.cia --- Installed

0004003020008802.cia

fsException:

fs.cpp:117 Result: 0xD8E0806A

Failed to write to file!

Did you store the update files in '/updates'?
```

I'm using the 3DSX version on Luma3DS. Tried multiple times.
Thank you.

**Comment by profi200** [comment]
The files you used are broken or your SD card is corrupted. Make sure the files match the hash provided by the source (if any) and and that the SD card is freshly formatted.

**Comment by ghost** [comment]
The same issue occurs on another SD card which was freshly formatted. The MD5 hash matches what was provided to me. I don't exactly know why this occurs, but, in the end, it is likely user error.
