### ISSUE TITLE
How to install cia in sysnand ?

### ISSUE THREAD

**Issue by rogertranchez** [profi200/sysUpdater#6]
Hello, i have downgraded my emunand with sysupdater.cia successfully , but I don't know how to install it on rxtool devmode, because the install in devmode from fbi  works ok , but i cannot see the icon for your app like I see it when I installed it on emunand, so I cannot downgrade sysnand. Thanks in advance !!!

**Comment by profi200** [comment]
It will only work if signature checks are disabled. Make sure you boot into sysNAND with patched signature checks.
