### ISSUE TITLE
Corrupted zip.

### ISSUE THREAD

**Issue by mariohackandglitch** [profi200/sysUpdater#7]
The release 0.4.1 zip is corrupted, I get error 0x80004005 while trying to extract it. I tried with winrar and windows explorer, both can't extract. Which program did you use for generating the zip?

**Comment by profi200** [comment]
It may be because i used LZMA as compression method. 7-Zip supports it but not sure about other unpackers.

**Comment by profi200** [comment]
The next release will use zips compressed with deflate instead so this should be fine.

**Comment by profi200** [comment]
Latest release should extract fine with everything.
