### ISSUE TITLE
Would this work on my dev unit 3DS? (QUESTION)

### ISSUE THREAD

**Issue by KashiToxicBlood** [profi200/sysUpdater#9]
I know i'm a familiar face from the Project_CTR  issue, this is not really an issue but more a question, I compiled sysUpdater and signed it with devkeys, installed the .cia file to my dev unit 3DS, (I also took a screenshot with the Test Menu if you would like to use this image for future references ---> http://i.imgur.com/lJ8FKmd.png?1 ) I have the latest system update cia from the latest CTR-SDK 11.4.0 and extracted update cia files from the .csu files, my question is would sysUpdater even work? or would it just give me a hardbrick? I'm asking this mainly because FBI doesn't work on dev units so I just wanna make sure if this could possibly work on it.

**Comment by profi200** [comment]
I can't guarantee it will work but on the other hand i see no reason it should not work provided all used services are there and the title version check works correctly. It requires the standard services most apps should have access to + am:u or am:net.

How does FBI fail? That could useful to know.

**Comment by Reisyukaku** [comment]
A lot of dev system apps have different title IDs, and i believe this is one reason why FBI doesnt work. Basically from my observations, the last digit of the TID low means this:
1 = dev
2 = retail
3 = retail (safemode)
(i.e AM service on dev is 00001501)

**Comment by profi200** [comment]
What you are talking about is the TitleID Variation: http://3dbrew.org/wiki/Title_list (scroll down)

I was hoping for high res pics. Especially the second gamecard slot is interesting and how it is connected to the SoC.
